# pandas-数据读入与数据框-19

## 通过文件读入dataframe

* 注意源文件是否有列标，没有的时候可以自己用names补充

In [1]:
import numpy as np
import pandas as pd

In [3]:
r1=pd.read_csv(r"D:\t_alibaba_data3.txt",names=["user","brand","behavr","date"],sep="\t",dtype={"behavr":int})
#pandas会自己判断数据类型，但是有时也需要自己额外指定数据类型（比如当存在数字id时我们通常希望把id当成字符串），这里我们指定了behavr为整数

In [8]:
r1.head(2)
#数据读入结果通常包含行标；列标，元素三个部分，其中行标通常使用隐式索引而列表自定义或者使用数据自带
#这样一个数据的读入结果称之为数据框（DataFrame）

user  brand  behavr   date
0  10944750  13451       0  06/04
1  10944750  13451       2  06/04

课间作业：

1，请导入pandas与numpy两个包

2，请读入t_alibaba_data3.txt数据并输出前5行；

3，请创建一个有5个元素的序列Series，具体值随意

4，请创建一个字典并将其转换为序列；请输出此序列的所有值与所有索引

## DataFrame的自定义

* 一个二维数组并且横向与纵向都有自定义索引
* dataframe可以看成一系列有相同索引的series（序列有哪些特性？相比列表与字典）
* 数据框的三个部分：元素，行标，列表

In [5]:
np.random.randn(5,3)

array([[-0.696596  ,  0.56342855,  0.26144675],
       [-0.03113069,  0.70914332,  0.11477352],
       [ 0.21250445, -0.02899547,  1.38679922],
       [ 0.82623891,  0.76206225, -0.54906904],
       [-2.07269104, -0.75800511, -0.25333567]])

In [9]:
a=pd.DataFrame(np.random.randn(5,3),index=range(2,7), columns=["a","b","c"])#相对数组增加了横向和纵向的自定义索引，双索引机制
a

a         b         c
2  1.182523 -0.161965 -0.409237
3  0.645736 -0.730600  0.110270
4 -1.729206 -0.809722  0.531144
5 -0.365480 -1.252131 -0.682597
6  0.242038 -2.430392  1.005385

In [11]:
#各种缺省定义
a=pd.DataFrame(np.random.randn(5,3),index=range(2,7))
a

0         1         2
2 -0.611727  0.878164 -1.719476
3 -0.129030 -0.551584  0.001111
4 -0.124454 -1.109925 -0.573910
5 -1.500460  0.539815  1.115550
6  0.754432 -1.353711  0.978113

In [10]:
a=pd.DataFrame(np.random.randn(5,3))
a

0         1         2
0  0.177805  0.487744 -1.112313
1 -0.202860 -0.680344 -0.419452
2  0.951385 -1.030348 -1.246392
3  0.352769 -0.339491  0.620877
4  1.985234  0.776287  0.135577

## 数据框各部分的调取

* values
* index
* columns

In [10]:
a=pd.DataFrame(np.random.randn(5,3),index=range(2,7), columns=["a","b","c"])
a

a         b         c
2  1.344393  0.093702 -0.764847
3  0.501674  0.737908  0.353089
4 -1.506748 -0.328498  1.834636
5  0.230217 -2.703300  0.156680
6  0.944292  0.284977  0.377684

In [11]:
a.values

array([[ 1.344393  ,  0.09370241, -0.76484683],
       [ 0.50167366,  0.73790845,  0.35308927],
       [-1.50674773, -0.3284977 ,  1.8346364 ],
       [ 0.23021725, -2.70330017,  0.15668025],
       [ 0.94429173,  0.28497682,  0.37768446]])

In [12]:
a.index

RangeIndex(start=2, stop=7, step=1)

In [13]:
a.columns

Index(['a', 'b', 'c'], dtype='object')

In [13]:
#可以改变列标
a.columns=[5,6,7]

In [14]:
a

5         6         7
2  1.344393  0.093702 -0.764847
3  0.501674  0.737908  0.353089
4 -1.506748 -0.328498  1.834636
5  0.230217 -2.703300  0.156680
6  0.944292  0.284977  0.377684

## 数据框的切片与双索引机制的影响

* 简单取列

* loc与iloc

In [8]:
a=pd.DataFrame(np.random.randn(5,3),index=range(2,7), columns=["a","b","c"])
a

a         b         c
2 -0.008392  2.307387  0.347331
3 -1.178206 -0.816691  1.182518
4 -0.477909  1.261472  0.855608
5  0.395608  0.109552  0.222928
6 -3.467202  0.019734  0.439538

In [6]:
a.a

2    0.605595
3    0.574022
4    1.203063
5    1.881800
6    1.219451
Name: a, dtype: float64

In [7]:
a["a"]#这样的简写只能用于取列，不能用于行标

2    0.605595
3    0.574022
4    1.203063
5    1.881800
6    1.219451
Name: a, dtype: float64

In [26]:
#a[2]

In [15]:
a[2:4]["a"]

4   -0.477909
5    0.395608
Name: a, dtype: float64

In [13]:
#a[2]

In [23]:
#a[2:4]
a.iloc[2:4]

a         b         c
4  0.572986 -1.750536  0.996885
5  1.218561  0.808883  0.325489

In [14]:
a.loc[2:4]#显式索引，包含头也包含尾部

a         b         c
2  0.605595 -0.158303 -0.847850
3  0.574022  1.049481 -1.532547
4  1.203063 -0.701662 -0.052133

In [31]:
a.a.loc[2:4]

2    0.637255
3   -0.427746
4    0.572986
Name: a, dtype: float64

In [35]:
a.loc[[2,3,4],["a","b"]]

a         b
2  0.637255  1.096799
3 -0.427746 -1.152904
4  0.572986 -1.750536

In [19]:
a.loc[:,["a","b"]].loc[2:4].a[2]

0.6055949134938302

In [30]:
a.loc[:,"a"]#基于显示索引;注意这里的符号都必须是英文符号

2    0.637255
3   -0.427746
4    0.572986
5    1.218561
6    0.286703
Name: a, dtype: float64

In [26]:
a.iloc[:,0]#基于隐式索引

2   -1.111760
3   -1.878672
4   -0.656579
5   -1.828484
6   -0.475407
Name: a, dtype: float64

In [21]:
a.loc[:,["a","c"]]

a         c
2 -0.008392  0.347331
3 -1.178206  1.182518
4 -0.477909  0.855608
5  0.395608  0.222928
6 -3.467202  0.439538

In [42]:
a.iloc[0:2,0:2]#隐式索引的优势在于有顺序

a         b
2  0.637255  1.096799
3 -0.427746 -1.152904

In [29]:
a.loc[[2,4],:]#注意这里不能2：5，显式索引没有顺序

a         b         c
2 -1.111760 -1.307730 -1.047525
4 -0.656579 -0.072623  0.626065

In [33]:
a.iloc[[2,4],:]#注意这里和上面的不同

a         b         c
4 -0.656579 -0.072623  0.626065
6 -0.475407  1.626150 -0.442536

In [44]:
a.loc[4,"a"]

0.5729856164359833

In [45]:
a.iloc[0,1]

1.096799460433495

* 课间作业

1，请创建一个5*4的数据框，其中的元素用随机数生成，行标与列标都用字母定义（具体字母随意）；
请分别输出此数据框的值，列标，行标；
请通过切片取出此数据框的第二列的整列元素，第三行整行元素，以及第四列第二行的元素；请切片整体输出第一，二，三行所有元素；
请切片整体输出第一列与第三列所有元素

2，请读入t_alibaba_data3.txt数据并输出前5行；请输出此数据的第51行到第58行；请输出此数据其中user整列；请输出数据中user与date这两列；请输出数据中user与date两列的第41到46行数据。


In [52]:
r1=pd.read_csv(r"D:\t_alibaba_data3\t_alibaba_data3.txt",names=["user","brand","behavr","date"],sep="\t",dtype={"behavr":int})
r1.head(4)

user  brand  behavr   date
0  10944750  13451       0  06/04
1  10944750  13451       2  06/04
2  10944750  13451       2  06/04
3  10944750  13451       0  06/04

In [56]:
r1.loc[51:59]

user  brand  behavr   date
51  10944750   7373       0  06/11
52  10944750   7373       0  06/11
53  10944750   7373       0  06/11
54  10944750   4078       0  05/15
55  10944750   8628       0  06/10
56  10944750   8628       0  06/10
57  10944750   8628       0  06/10
58  10944750   8628       0  06/10
59  10944750   8628       0  06/10

In [60]:
r1.loc[:,["user","date"]].loc[41:46]

user   date
41  10944750  07/07
42  10944750  06/14
43  10944750  06/14
44  10944750  06/14
45  10944750  06/28
46  10944750  05/16

In [36]:
pd.Series([2,3,5,1,2])

0    2
1    3
2    5
3    1
4    2
dtype: int64

In [41]:
b={2:3,4:3}
a=pd.Series(b)
a

2    3
4    3
dtype: int64

In [39]:
a.values

array([3, 3], dtype=int64)

In [40]:
a.index

Int64Index([2, 4], dtype='int64')

In [42]:
a=pd.DataFrame(np.random.randn(5,4),index=["e","f","g","h","y"], columns=["a","b","c","d"])
a

a         b         c         d
e  1.033013  0.596142 -0.893543  0.496052
f -1.512174  1.101601  0.997767  0.322629
g  0.306920  0.556080 -0.563244  1.034626
h -0.266105  0.642501 -1.659265  0.246395
y -2.804186  1.742886  1.506969  0.474481

In [45]:
a.index

Index(['e', 'f', 'g', 'h', 'y'], dtype='object')

In [47]:
a.loc[:,["a","c"]]

a         c
e  1.033013 -0.893543
f -1.512174  0.997767
g  0.306920 -0.563244
h -0.266105 -1.659265
y -2.804186  1.506969

## 数据框常用统计函数及其方向性

In [22]:
a=pd.DataFrame(np.random.randn(5,3),index=range(2,7), columns=["a","b","c"])
a

a         b         c
2  2.762720 -0.945071 -1.320045
3  0.723445  1.672914  1.872333
4  0.105960  0.830412 -1.549133
5  1.175456 -0.046056  0.068801
6 -1.249716  0.266825  1.314911

### 数据框的形状

In [4]:
len(a)#数据框的长度

5

In [7]:
len(a.loc[2,:])#宽度

3

In [23]:
a.b.size

5

In [33]:
a.size#元素总量

15

In [34]:
a.shape#矩阵维度

(5, 3)

### 统计函数

* 平均（mean）,求和（sum），最大值(max)，最小值(min)，中位数(median)，方差（var），标准差（std），累乘（prod），first,last,mean,median（中位数）,mad（均值绝对偏差）

* describe

In [24]:
a

a         b         c
2  2.762720 -0.945071 -1.320045
3  0.723445  1.672914  1.872333
4  0.105960  0.830412 -1.549133
5  1.175456 -0.046056  0.068801
6 -1.249716  0.266825  1.314911

In [34]:
a.std()

a    1.469323
b    0.977460
c    1.529032
dtype: float64

In [31]:
a.b.mean()

0.35580486907292463

In [35]:
a.mean(axis=1)

2    0.165868
3    1.422897
4   -0.204254
5    0.399401
6    0.110673
dtype: float64

In [27]:
a.sum()

a   -0.671792
b   -1.874512
c   -1.603379
dtype: float64

In [27]:
a.sum(axis=1)

2    1.985066
3    1.645004
4   -0.466485
5   -2.469435
6    1.449763
dtype: float64

In [40]:
a.var()

a    1.282429
b    0.942127
c    2.042687
dtype: float64

In [38]:
#这是一个集成统计函数
a.describe().b["std"]

0.9774602715437708

In [41]:
#自定义的集成统计函数
a.agg(["min","max","sum","std","median"])

a         b         c
min    -1.249716 -0.945071 -1.549133
max     2.762720  1.672914  1.872333
sum     3.517865  1.779024  0.386868
std     1.469323  0.977460  1.529032
median  0.723445  0.266825  0.068801

## 课间题

1，已知如下矩阵，请把此矩阵转化为数据框a，列标用字母，行标用默认的顺序索引

2，求上面数据框每列与每行的平均值

3，求第2列的和

4，求出每列的中位数

5，通过agg同时求出每列的均值，方差，中位数

6，使用describe函数求出各个分位数

7， 请读入t_alibaba_data3.txt数据。请输出数据的总行数，总列数，输出记录对应最大日期与最小日期

In [50]:
aj=np.array([[8, 4, 3, 4],
       [5, 7, 4, 3],
       [5, 3, 4, 7],
       [7, 7, 5, 8],
       [5, 4, 4, 5],
       [7, 5, 7, 6]])

In [48]:
a1=pd.DataFrame(aj,columns=["a","b","c","d"])

## 数据框的比较过滤

* 比较都是以列为基础的
* 大于小于，与或非，等于也是==

In [51]:
a

a         b         c
2  2.762720 -0.945071 -1.320045
3  0.723445  1.672914  1.872333
4  0.105960  0.830412 -1.549133
5  1.175456 -0.046056  0.068801
6 -1.249716  0.266825  1.314911

In [52]:
a[a>0]

a         b         c
2  2.762720       NaN       NaN
3  0.723445  1.672914  1.872333
4  0.105960  0.830412       NaN
5  1.175456       NaN  0.068801
6       NaN  0.266825  1.314911

In [55]:
a[a>1]

a         b         c
2  2.762720       NaN       NaN
3       NaN  1.672914  1.872333
4       NaN       NaN       NaN
5  1.175456       NaN       NaN
6       NaN       NaN  1.314911

In [33]:
a[a>0].values

array([[       nan, 0.97968696, 1.19249707],
       [0.23427496, 0.02527908,        nan],
       [       nan,        nan,        nan],
       [1.56276833,        nan,        nan],
       [       nan,        nan,        nan]])

In [57]:
a[a.a>-1]

a         b         c
2  2.762720 -0.945071 -1.320045
3  0.723445  1.672914  1.872333
4  0.105960  0.830412 -1.549133
5  1.175456 -0.046056  0.068801

In [58]:
a[(a.a>-1)&(a.b<0)]

a         b         c
2  2.762720 -0.945071 -1.320045
5  1.175456 -0.046056  0.068801

In [ ]:
a.a==1

In [59]:
a[(a.a>-1)|(a.c>1)]

a         b         c
2  2.762720 -0.945071 -1.320045
3  0.723445  1.672914  1.872333
4  0.105960  0.830412 -1.549133
5  1.175456 -0.046056  0.068801
6 -1.249716  0.266825  1.314911

1，已知如下矩阵，请把此矩阵转化为数据框a，列标用字母，行标用默认的顺序索引

2，请取出此数据框的第二列，并求出这一列的平均值

3，求数据每列的和；每行的方差

4，输出数据中第三列数等于4的行

5, 输出所有在5到8之间的元素，包含首尾

6，用describe函数统计每列的特征

In [7]:
aj=np.array([[8, 4, 3, 4],
       [5, 7, 4, 3],
       [5, 3, 4, 7],
       [7, 7, 5, 8],
       [5, 4, 4, 5],
       [7, 5, 7, 6]])

In [28]:
aj=np.array([[8, 4, 3, 4],
       [5, 7, 4, 3],
       [5, 3, 4, 7],
       [7, 7, 5, 8],
       [5, 4, 4, 5],
       [7, 5, 7, 6]])

In [29]:
a1=pd.DataFrame(aj,columns=["a","b","c","d"])

In [30]:
a1

a  b  c  d
0  8  4  3  4
1  5  7  4  3
2  5  3  4  7
3  7  7  5  8
4  5  4  4  5
5  7  5  7  6

In [12]:
a1.b

0    4
1    7
2    3
3    7
4    4
5    5
Name: b, dtype: int32

In [13]:
a1.b.mean()

5.0

In [14]:
a1.sum()

a    37
b    30
c    27
d    33
dtype: int64

In [15]:
a1.var(axis=1)

0    4.916667
1    2.916667
2    2.916667
3    1.583333
4    0.333333
5    0.916667
dtype: float64

In [18]:
a1[a1.c==4]

a  b  c  d
1  5  7  4  3
2  5  3  4  7
4  5  4  4  5

In [19]:
a1[(a1>5)&(a1<8)]

a    b    c    d
0  NaN  NaN  NaN  NaN
1  NaN  7.0  NaN  NaN
2  NaN  NaN  NaN  7.0
3  7.0  7.0  NaN  NaN
4  NaN  NaN  NaN  NaN
5  7.0  NaN  7.0  6.0

In [20]:
a1.describe()

a        b         c         d
count  6.000000  6.00000  6.000000  6.000000
mean   6.166667  5.00000  4.500000  5.500000
std    1.329160  1.67332  1.378405  1.870829
min    5.000000  3.00000  3.000000  3.000000
25%    5.000000  4.00000  4.000000  4.250000
50%    6.000000  4.50000  4.000000  5.500000
75%    7.000000  6.50000  4.750000  6.750000
max    8.000000  7.00000  7.000000  8.000000